### ISSUE TITLE
몸통박치기 구현과 사망 / 부활 시스템

### ISSUE THREAD

**Issue by Cornminator** [virtus2/project-gamma#4]

**Comment by virtus2** [comment]
몸통박치기 구현 완료
원래는 돌진 사용 후 일정시간 동안 부딪히면 몸통박치기 판정돼서 잉크 터뜨리는 걸로 했으나
현재 돌진 쿨타임동안에만 박으면 판정 인정되는 버그가 있음
수정 예정

**Comment by Cornminator** [comment]
완전섹스네..


2023년 7월 24일 (월) 오전 12:56, Kim Hyun Deok ***@***.***>님이 작성:
